### PR TITLE
Calculate lap correctly to replace worker in isolation mode

### PR DESCRIPTION
**Pull request by aeroastro**
@grosser 

This fix the `isolation` bug in #244

Since the `lap` in the PR was a local variable, it could not correctly count the lap for each worker, and resulted in never-replaceable workers.

This patch fix the bug by using instance variable `@lap` of `Worker`.

### CODE REVIEW

**Comment by grosser** [comment]
ah ... tricky ... so we need a better test for isolation too ? (that fails without these changes)

**Comment by aeroastro** [comment]
OK. I will add it.

**Comment by aeroastro** [comment]
Actually, there are already tests on this isolation.

https://github.com/grosser/parallel/blob/a7138afd7f739a7d4e02c987e7030f86f220b521/spec/cases/map_isolation.rb#L3-L8

Current implementation also have a bug on assigning worker. I have fixed it too.

**Comment by aeroastro** [comment]
Following are the simple execution of the code.

## current master

```
$ bundle exec ruby spec/cases/map_isolation.rb
1
2
1
1
OK
```

## this branch

```
$ bundle exec ruby spec/cases/map_isolation.rb
1
2
3
4
OK
```

**Comment by grosser** [comment]
... I'll fix the existing testcase then

**Comment by aeroastro** [comment]
Thank you for merging this ❤️

**Comment by grosser** [comment]
`skip if ENV['TRAVIS'] # this randomly hangs on travis` <- oh boy :D

**Comment by grosser** [comment]
thx for fixing a nasty bug :D
trying to re-enable the test here https://github.com/grosser/parallel/pull/252

**Comment by grosser** [comment]
1.16.1

**Pull request merged**
