### PR TITLE
Assign worker averagely

### PR DESCRIPTION
**Pull request by rueyaa332266**
Hi @grosser 

I found an issue when assigning jobs to workers.
Not happen every time, but sometime when printing worker number, few workers work obviously more than others and some workers have no job to work.

Here are some examples:
```ruby
Parallel.each(0...5, :in_processes =>5) { |i| puts "Worker: #{Parallel.worker_number}" }
Worker: 0
Worker: 0
Worker: 0
Worker: 2
Worker: 1
```
```ruby
Parallel.each(0...5, :in_processes =>5) { |i| puts "Worker: #{Parallel.worker_number}" }
Worker: 0
Worker: 1
Worker: 2
Worker: 0
Worker: 3
```

I realize that when some child process or thread works faster than others,`job_factory.next` will execute more times than others.
So the worker aren't assigned averagely. 

I fix the code by adding the max work times limit in the loop, so workers can be assigned averagely.

Let me know if you have any suggestion. Thanks!

### CODE REVIEW

**Comment by grosser** [comment]
won't that make things slower if there is for example 2 workers with 1 slow item and 9 fast items ? (as in the 5 fast items will get processed and then it would wait for the slow worker to finish and do 4 more fast items)

**Comment by rueyaa332266** [comment]
Totally agree with you. Worker choose the faster way to assign rather than assign averagely.
I got that, thanks!

Actually I'm working on something that I want workers to got equivalence item to work not depend on speed.
Would you mind that I will change this assign averagely feature into an option just like `isolation: true`.

**Comment by grosser** [comment]
hmmm I'm not a big fan since this sounds very 1-off-usecase and adds edge-cases/maintenance/etc for other users

what exactly is the usecase that needs average items ? ... can it maybe just sleep after being done to not unblock the worker ?

**Comment by rueyaa332266** [comment]
I'm making some tests with "test/unit" and creating test classes in parallel.

test/unit cases run after every worker assigned. And these cases needs some times to run. So when some workers get more cases than others, it becomes not so efficient. 

The usecase is like this:
```ruby
require 'test/unit'
require 'parallel'

class Example < Test::Unit::TestCase
end

def work(case_name)
  Example.class_eval %Q"def test_#{case_name}; p 'work'; end"
end

Parallel.each(0...4, :in_processes => 2) do |i|
    work(i)
    puts "Worker: #{Parallel.worker_number}"
end

### output ###
Worker: 1
Worker: 1
Worker: 0
Worker: 1
Loaded suite test
Started
"work"
."work"
."work"
.
Finished in 0.000694 seconds.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
3 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
4322.77 tests/s, 0.00 assertions/s
Loaded suite test
Started
"work"
.
Finished in 0.00144 seconds.
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
694.44 tests/s, 0.00 assertions/s
```

**Comment by rueyaa332266** [comment]
Hi, @grosser. I updated the usecase.
Do you have any advise?
Or is it not a good idea to use test/unit in parallel.

**Comment by grosser** [comment]
uses https://github.com/grosser/parallel_tests or https://github.com/grosser/parallel_split_test ?

**Comment by rueyaa332266** [comment]
I'll check them! Thanks for your help.
Close this pull request.

**Pull request closed without merging**
