### PR TITLE
reconnect

### PR DESCRIPTION
**Pull request by grosser**
parking this here until I can confirm this works ... maybe needs some tests ...

### CODE REVIEW

**Comment by seanarnold** [comment]
This didn't fix it for me :(

```
ActiveRecord::StatementInvalid: PG::UnableToSend: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

**Comment by grosser** [comment]
meh :(

does this work ?
```Ruby
disconnect
Parallel do
  connect
end
```

**Comment by Daniel-ltw** [comment]
```ruby
ActiveRecord::Base.connection_pool.with_connection
```

Have you guys tried something like this?

**Comment by grosser** [comment]
that looks nice ... better then disconnect/reconnect for sure ... would be great to have a failing spec and then a fix that can be triggered by and option like `active_record: :reconnect`

**Comment by Daniel-ltw** [comment]
Also from the looks of it, this is orm dependent and it only applies to ActiveRecord. 

If you are looking at a wider audience, maybe try supporting Sequel and ROM as well.

**Comment by grosser** [comment]
let's fix the 99% usecase first :D
next important would be reconnecting redis afaik

**Comment by Daniel-ltw** [comment]
The other question I have is, if this is a requirement of the gem? 

Another way to put this is, is the gem required to reconnect to the database? 
Is reconnecting to the database a responsibility of the gem?

**Comment by seanarnold** [comment]
Before this goes anywhere it would be good to add some tests.

@Daniel-ltw that suggestion is already on the README. Maybe that is enough?
I agree that this shouldn't choose a single ORM, and the Gem says it's for 'Ruby' not Rails, so maybe the README section about ActiveRecord is enough?

**Comment by steakknife** [comment]
Btw, having issues using parallel with sequel (`SQLite3::SQLException: no such table: {{tablename}} (Sequel::DatabaseError)` (works without parallel)

**Pull request closed without merging**
